from .auth import router as auth_router
from .books import router as books_router
from .users import router as users_router
from .wishlist import router as wishlist_router
from .borrows import router as borrows_router
from .chatbot import router as chatbot_router
from .admin_stats import router as admin_stats_router
from .notifications import router as notifications_router
from .reviews import router as reviews_router
from .platform import router as platform_router
from .events_lab import router as events_lab_router
from .library_info import router as library_info_router
from .dashboard import router as dashboard_router
